#!/bin/bash

echo "" > all.txt

for i in *.html; do
    [ -f "$i" ] || break
	echo "" >> all.txt
	echo "$i" | sed 's/.....$//' >> all.txt
	echo "проекты:" >> all.txt
    fgrep -A 1 'shared the project' "$i" | fgrep 'href="/projects/' | sed -E 's:.*href="/projects/([0-9]+).*:\1:' | sort -rg | uniq >> all.txt
	echo "ремиксы:" >> all.txt
    fgrep -A 1 'remixed' "$i" | fgrep 'href="/projects/' | sed -E 's:.*href="/projects/([0-9]+).*:\1:' | sort -rg | uniq >> all.txt
done
